name: CD
on:
    push:
        branches:
            - master
jobs:
    cd:
        steps:
            - name: Install dependencies
              run: npm i

            - name: Build
              run: npm run deploy
